.TH "src/service Directory Reference" 3 "Fri Sep 22 2023" "Version v0.1" "API de Paris - Documentation du Gestionnaire" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/service Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBperiodicFetcher\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsignalHandler\&.cpp\fP"
.br
.in -1c
