.TH "include/storage Directory Reference" 3 "Fri Sep 22 2023" "Version v0.1" "API de Paris - Documentation du Gestionnaire" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/storage Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdataStorage\&.h\fP"
.br
.RI "Provides the \fBDataStorage\fP class for handling data persistence in JSON format\&. "
.in -1c
