.TH "src/connectApi Directory Reference" 3 "Fri Sep 22 2023" "Version v0.1" "API de Paris - Documentation du Gestionnaire" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/connectApi Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBapiHandler\&.cpp\fP"
.br
.ti -1c
.RI "file \fBconcreteObserver\&.cpp\fP"
.br
.ti -1c
.RI "file \fBobservable\&.cpp\fP"
.br
.in -1c
