.TH "include/service Directory Reference" 3 "Fri Sep 22 2023" "Version v0.1" "API de Paris - Documentation du Gestionnaire" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/service Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfetchIntervalTimeUnit\&.h\fP"
.br
.RI "Provides utility macros and definitions related to time interval units\&. "
.ti -1c
.RI "file \fBperiodicFetcher\&.h\fP"
.br
.RI "Provides the \fBPeriodicFetcher\fP class for periodic data fetching and processing\&. "
.ti -1c
.RI "file \fBsignalHandler\&.h\fP"
.br
.RI "Provides a singleton-based handler for system signals\&. "
.in -1c
