.TH "include Directory Reference" 3 "Fri Sep 22 2023" "Version v0.1" "API de Paris - Documentation du Gestionnaire" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBconnectApi\fP"
.br
.ti -1c
.RI "directory \fBfileManagement\fP"
.br
.ti -1c
.RI "directory \fBgdGeneration\fP"
.br
.ti -1c
.RI "directory \fBservice\fP"
.br
.ti -1c
.RI "directory \fBstorage\fP"
.br
.in -1c
