.TH "Color" 3 "Fri Sep 22 2023" "Version v0.1" "API de Paris - Documentation du Gestionnaire" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Color \- Structure to represent a color in the RGB color space\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphicsUtils\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBr\fP"
.br
.RI "Red component of the color, in the range 0-255\&. "
.ti -1c
.RI "int \fBg\fP"
.br
.RI "Green component of the color, in the range 0-255\&. "
.ti -1c
.RI "int \fBb\fP"
.br
.RI "Blue component of the color, in the range 0-255\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure to represent a color in the RGB color space\&. 

This structure is used to define a color using its red (r), green (g), and blue (b) components\&. It can be used to represent a specific color for various graphical elements\&. 
.PP
Definition at line \fB23\fP of file \fBGraphicsUtils\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Color::b"

.PP
Blue component of the color, in the range 0-255\&. 
.PP
Definition at line \fB27\fP of file \fBGraphicsUtils\&.h\fP\&.
.SS "int Color::g"

.PP
Green component of the color, in the range 0-255\&. 
.PP
Definition at line \fB26\fP of file \fBGraphicsUtils\&.h\fP\&.
.SS "int Color::r"

.PP
Red component of the color, in the range 0-255\&. 
.PP
Definition at line \fB25\fP of file \fBGraphicsUtils\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for API de Paris - Documentation du Gestionnaire from the source code\&.
