.TH "include/service/fetchIntervalTimeUnit.h" 3 "Fri Sep 22 2023" "Version v0.1" "API de Paris - Documentation du Gestionnaire" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/service/fetchIntervalTimeUnit.h \- Provides utility macros and definitions related to time interval units\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFetchIntervalTimeUnit\fP"
.br
.RI "Contains definitions related to time unit intervals\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBFetchIntervalTimeUnit::fitu\fP { \fBFetchIntervalTimeUnit::SEC\fP, \fBFetchIntervalTimeUnit::MIN\fP, \fBFetchIntervalTimeUnit::HR\fP, \fBFetchIntervalTimeUnit::UNKNOWN\fP }"
.br
.RI "Enumeration to represent different time interval units\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides utility macros and definitions related to time interval units\&. 


.PP
\fBAuthor\fP
.RS 4
Antony Coco (antony.coco.pro@gmail.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2023-09-22 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.PP
Definition in file \fBfetchIntervalTimeUnit\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for API de Paris - Documentation du Gestionnaire from the source code\&.
