.TH "FetchIntervalTimeUnit" 3 "Fri Sep 22 2023" "Version v0.1" "API de Paris - Documentation du Gestionnaire" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FetchIntervalTimeUnit \- Contains definitions related to time unit intervals\&.  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBfitu\fP { \fBSEC\fP, \fBMIN\fP, \fBHR\fP, \fBUNKNOWN\fP }"
.br
.RI "Enumeration to represent different time interval units\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains definitions related to time unit intervals\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBFetchIntervalTimeUnit::fitu\fP"

.PP
Enumeration to represent different time interval units\&. This enumeration provides different units of time that can be used throughout the application to denote intervals for fetching or any other time-related functionality\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISEC \fP\fP
Represents seconds\&. 
.TP
\fB\fIMIN \fP\fP
Represents minutes\&. 
.TP
\fB\fIHR \fP\fP
Represents hours\&. 
.TP
\fB\fIUNKNOWN \fP\fP
Represents an unknown or unspecified time unit\&. 
.PP
Definition at line \fB22\fP of file \fBfetchIntervalTimeUnit\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for API de Paris - Documentation du Gestionnaire from the source code\&.
