.TH "include/connectApi/observable.h" 3 "Fri Sep 22 2023" "Version v0.1" "API de Paris - Documentation du Gestionnaire" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/connectApi/observable.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <map>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <unordered_set>\fP
.br
\fC#include <nlohmann/json\&.hpp>\fP
.br
\fC#include 'observer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBObservable\fP"
.br
.RI "Represents the subject (or observable) in the \fBObserver\fP design pattern\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for API de Paris - Documentation du Gestionnaire from the source code\&.
