.TH "PieChartSegment" 3 "Fri Sep 22 2023" "Version v0.1" "API de Paris - Documentation du Gestionnaire" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PieChartSegment \- Structure to represent a segment in a pie chart\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PieChartGenerator\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBpercentage\fP"
.br
.RI "The percentage that this segment represents in the pie chart\&. "
.ti -1c
.RI "std::string \fBlabel\fP"
.br
.RI "The label for this segment (e\&.g\&., the name of the category)\&. "
.ti -1c
.RI "\fBColor\fP \fBcolor\fP"
.br
.RI "The color used to draw this segment in the pie chart\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure to represent a segment in a pie chart\&. 

This structure is used to define a segment of a pie chart, including its percentage representation, label, and color\&. 
.PP
Definition at line \fB40\fP of file \fBPieChartGenerator\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBColor\fP PieChartSegment::color"

.PP
The color used to draw this segment in the pie chart\&. 
.PP
Definition at line \fB43\fP of file \fBPieChartGenerator\&.h\fP\&.
.SS "std::string PieChartSegment::label"

.PP
The label for this segment (e\&.g\&., the name of the category)\&. 
.PP
Definition at line \fB42\fP of file \fBPieChartGenerator\&.h\fP\&.
.SS "double PieChartSegment::percentage"

.PP
The percentage that this segment represents in the pie chart\&. 
.PP
Definition at line \fB41\fP of file \fBPieChartGenerator\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for API de Paris - Documentation du Gestionnaire from the source code\&.
