.TH "include/gdGeneration/utils.h" 3 "Fri Sep 22 2023" "Version v0.1" "API de Paris - Documentation du Gestionnaire" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/gdGeneration/utils.h \- Provides utility macros and definitions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMIN\fP(a,  b)   ((a) < (b) ? (a) : (b))"
.br
.RI "Macro to determine the minimum of two values\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides utility macros and definitions\&. 


.PP
\fBAuthor\fP
.RS 4
Antony Coco (antony.coco.pro@gmail.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2023-09-22 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023
.RE
.PP
This header defines utility macros and functions that can be reused across different parts of the project\&. 
.PP
Definition in file \fButils\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define MIN(a, b)   ((a) < (b) ? (a) : (b))"

.PP
Macro to determine the minimum of two values\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP First value\&. 
.br
\fIb\fP Second value\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The lesser value between a and b\&. 
.RE
.PP

.PP
Definition at line \fB23\fP of file \fButils\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for API de Paris - Documentation du Gestionnaire from the source code\&.
